# Generated by Django 3.2.3 on 2021-06-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamentoData', models.DateField()),
                ('agendamentoHora', models.TimeField()),
                ('agendamentoDescricao', models.TextField()),
                ('agendamentoNome', models.TextField()),
            ],
        ),
    ]
