# Generated by Django 3.2.3 on 2021-06-09 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_agendamento'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agendamento',
            table='agendamento',
        ),
    ]
