# Generated by Django 3.2.3 on 2021-06-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_agendamento_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='agendamentoMarcado',
            field=models.BooleanField(default=False),
        ),
    ]
