# Generated by Django 3.2.3 on 2021-06-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_agendamento_agendamentomarcado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['agendamentoData']},
        ),
    ]
