# Generated by Django 3.2.3 on 2021-06-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_agendamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={},
        ),
    ]
