# Generated by Django 3.2.3 on 2021-06-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210615_1141'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agendamento',
            table='agendamento',
        ),
    ]
