# Generated by Django 3.2.3 on 2021-06-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_agendamento_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agendamento',
            table='agendamento',
        ),
    ]
