# Generated by Django 3.2.3 on 2021-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_agendamento_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='agendamentoMarcado',
            field=models.BooleanField(choices=[(True, 'Confirmado'), (False, 'Aguardando confirmação')], default=False),
        ),
    ]
